path: /home/etmphile/桌面/RM2025-Radar-Algorithm/training_data/RM2025-Armor-Public-Dataset
train: train/images
val: val/images
test: test/images
names:
  0: disabled_armor
  1: red_armor
  2: blue_armor